package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"

	"github.com/palocortao/youtube-transcript-api-go/pkg/yt_transcript"
	"github.com/palocortao/youtube-transcript-api-go/pkg/yt_transcript_formatters"
)

func main() {
	var (
		languages              = flag.String("languages", "en", "Comma-separated list of language codes")
		formatter              = flag.String("formatter", "json", "Formatter to use (json, text)")
		preserveFormatting     = flag.Bool("preserve-formatting", true, "Preserve formatting")
		withTimestamps         = flag.Bool("with-timestamps", true, "Include timestamps")
		withLanguageCode       = flag.Bool("with-language-code", true, "Include language code")
		excludeManuallyCreated = flag.Bool("exclude-manually-created", false, "Exclude manually created subtitles") // not in use yet
		excludeAutoGenerated   = flag.Bool("exclude-auto-generated", false, "Exclude auto-generated subtitles")     // not in use yet
		logLevel               = flag.String("log-level", "error", "Log level (debug, info, warn, error)")
	)
	flag.Parse()

	if flag.NArg() < 1 {
		fmt.Println("Please provide at least one video ID")
		os.Exit(1)
	}

	if *excludeManuallyCreated && *excludeAutoGenerated {
		fmt.Println("Cannot exclude both manually created and auto-generated subtitles")
		os.Exit(1)
	}

	var level slog.Level
	if err := level.UnmarshalText([]byte(*logLevel)); err != nil {
		fmt.Printf("Invalid log level %q: %v\n", *logLevel, err)
		os.Exit(1)
	}

	var outputFormatter yt_transcript_formatters.Formatter

	if *formatter == "text" {
		outputFormatter = yt_transcript_formatters.NewTextFormatter(
			yt_transcript_formatters.WithTimestamps(*withTimestamps),
			yt_transcript_formatters.WithLanguageCode(*withLanguageCode),
		)
	} else {
		outputFormatter = yt_transcript_formatters.NewJSONFormatter(
			yt_transcript_formatters.WithTimestamps(*withTimestamps),
			yt_transcript_formatters.WithLanguageCode(*withLanguageCode),
		)
	}

	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: level}))

	client := yt_transcript.NewClient(
		yt_transcript.WithFormatter(outputFormatter),
		yt_transcript.WithLogger(logger),
	)

	videoID := flag.Arg(0)
	t, err := client.GetFormattedTranscripts(context.Background(), videoID, []string{*languages}, *preserveFormatting)

	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("%s", t)
	os.Exit(0)
}
