package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/horiagug/youtube-transcript-api-go/pkg/yt_transcript"
	"github.com/horiagug/youtube-transcript-api-go/pkg/yt_transcript_formatters"
)

func main() {
	var (
		languages              = flag.String("languages", "en", "Comma-separated list of language codes")
		formatter              = flag.String("formatter", "json", "Formatter to use (json, text)")
		preserveFormatting     = flag.Bool("preserve-formatting", true, "Preserve formatting")
		withTimestamps         = flag.Bool("with-timestamps", true, "Include timestamps")
		withLanguageCode       = flag.Bool("with-language-code", true, "Include language code")
		excludeManuallyCreated = flag.Bool("exclude-manually-created", false, "Exclude manually created subtitles") // not in use yet
		excludeAutoGenerated   = flag.Bool("exclude-auto-generated", false, "Exclude auto-generated subtitles")     // not in use yet
	)
	flag.Parse()

	if flag.NArg() < 1 {
		fmt.Println("Please provide at least one video ID")
		os.Exit(1)
	}

	if *excludeManuallyCreated && *excludeAutoGenerated {
		fmt.Println("Cannot exclude both manually created and auto-generated subtitles")
		os.Exit(1)
	}

	var outputFormatter yt_transcript_formatters.Formatter

	if *formatter == "text" {
		outputFormatter = yt_transcript_formatters.NewTextFormatter(
			yt_transcript_formatters.WithTimestamps(*withTimestamps),
			yt_transcript_formatters.WithLanguageCode(*withLanguageCode),
		)
	} else {
		outputFormatter = yt_transcript_formatters.NewJSONFormatter(
			yt_transcript_formatters.WithTimestamps(*withTimestamps),
			yt_transcript_formatters.WithLanguageCode(*withLanguageCode),
		)
	}

	client := yt_transcript.NewClient(
		yt_transcript.WithFormatter(outputFormatter),
	)

	videoID := flag.Arg(0)
	t, err := client.GetFormattedTranscripts(videoID, []string{*languages}, *preserveFormatting)

	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("%s", t)
	os.Exit(0)
}
